queries = {
    "AISLADEROS": """
        SELECT DISTINCT B.G3E_FID, I.CODIGO, B.CODIGO_OPERATIVO, A.CIRCUITO,B.REGION,
            CASE WHEN A.TENSION >= '13.8' THEN '2'
                 WHEN A.TENSION = '34.5' THEN '3'
                 WHEN A.TENSION <= '115' THEN '4' END NIVEL_TENSION,
            B.ZONAID, B.FID_ANTERIOR, B.MUNICIPIO, B.UBICACION, B.CONTRATO_INSTALACION,
            B.FECHA_OPERACION, I.CAPACIDAD,I.TIPO_AISLADERO,B.UC, B.COOR_GPS_LON, B.COOR_GPS_LAT
        FROM CCOMUN@GTECH B
        JOIN CCONECTIVIDAD_E@GTECH A ON B.G3E_FID = A.G3E_FID
        JOIN EAISLADE_AT@GTECH I ON I.G3E_FID = B.G3E_FID
        WHERE B.ESTADO = 'OPERACION'  AND A.CIRCUITO = :circuito AND B.REGION = :regional
    """,
    "CUCHILLAS": """
        SELECT DISTINCT B.G3E_FID, I.CODIGO, B.CODIGO_OPERATIVO, A.CIRCUITO,B.REGION,
            CASE WHEN A.TENSION >= '13.8' THEN '2'
                 WHEN A.TENSION = '34.5' THEN '3'
                 WHEN A.TENSION <= '115' THEN '4' END NIVEL_TENSION,
            B.ZONAID, B.MUNICIPIO, B.UBICACION, B.CONTRATO_INSTALACION, B.FECHA_OPERACION,
            B.UC, B.COOR_GPS_LON, B.COOR_GPS_LAT
        FROM CCOMUN@GTECH B
        JOIN CCONECTIVIDAD_E@GTECH A ON B.G3E_FID = A.G3E_FID
        JOIN ECUCHILL_AT@GTECH I ON I.G3E_FID = B.G3E_FID
        WHERE B.ESTADO = 'OPERACION'  AND A.CIRCUITO = :circuito AND B.REGION = :regional
    """,
    "RECONECTADORES": """
        SELECT DISTINCT B.G3E_FID, B.CODIGO_OPERATIVO, A.CIRCUITO,B.REGION,
            CASE WHEN A.TENSION >= '13.8' THEN '2'
                 WHEN A.TENSION = '34.5' THEN '3'
                 WHEN A.TENSION <= '115' THEN '4' END NIVEL_TENSION,
            B.ZONAID, B.MUNICIPIO, B.UBICACION, B.CONTRATO_INSTALACION, B.FECHA_OPERACION,
            B.UC, B.COOR_GPS_LON, B.COOR_GPS_LAT
        FROM CCOMUN@GTECH B
        JOIN CCONECTIVIDAD_E@GTECH A ON B.G3E_FID = A.G3E_FID
        JOIN ERECONEC_AT@GTECH I ON I.G3E_FID = B.G3E_FID
        WHERE B.ESTADO = 'OPERACION'  AND A.CIRCUITO = :circuito AND B.REGION = :regional
    """,
"TRAFOS": """
    SELECT 
        A.NODO_TRANSFORM_V, 
        B.G3E_FID, 
        B.ZONAID, 
        B.MUNICIPIO, 
        B.UBICACION,
        B.CONTRATO_INSTALACION, 
        B.FECHA_OPERACION, 
        C.NRO_TRANSFORMADOR_V, 
        A.FASES, 
        A.CIRCUITO,
        B.REGION,
        C.CODIGO, 
        C.FABRICANTE_TRAFO, 
        B.FECHA_FABRICACION, 
        C.TIPO_SUBESTACION,
        B.CLASIFICACION_MERCADO, 
        A.CAPACIDAD_NOMINAL, 
        B.OBSERVACIONES,
        B.COOR_GPS_LON, 
        B.COOR_GPS_LAT
    FROM CCOMUN@GTECH B
    JOIN CCONECTIVIDAD_E@GTECH A ON A.G3E_FID = B.G3E_FID
    JOIN ETRANSFO_AT@GTECH C ON B.G3E_FID = C.G3E_FID
    WHERE 
        A.G3E_FNO = 20400 
        AND B.ESTADO = 'OPERACION'  
        AND A.CIRCUITO = :circuito 
        AND B.REGION = :regional
""",
    "POSTES_MT": """
        SELECT DISTINCT C.G3E_FID, C.CODIGO, B.CODIGO_OPERATIVO,N.MACRONORMA,
            N.CIRCUITO,B.REGION, CASE WHEN Z.TENSION >= '13.8' THEN '2'
                             WHEN Z.TENSION = '34.5' THEN '3'
                             WHEN Z.TENSION <= '115' THEN '4' END NIVEL_TENSION,
            B.MUNICIPIO, B.UBICACION, B.CONTRATO_INSTALACION, B.CLASIFICACION_MERCADO,
            B.FECHA_INSTALACION, B.OBSERVACIONES, N.NORMA,
            CASE WHEN C.TIPO_INSTALACION IS NULL THEN 'Poste' ELSE C.TIPO_INSTALACION END APOYO,
            C.MATERIAL, C.ALTURA, E.TIPO_ADECUACION, C.RESISTENCIA_KGF, C.CODIGO CODIGO2, B.UC, E.TIPO_RED,
            B.COOR_GPS_LON,B.COOR_GPS_LAT
        FROM CCOMUN@GTECH B
        JOIN EPOSTE_AT@GTECH C ON B.G3E_FID = C.G3E_FID
        JOIN NORMA@GTECH N ON C.G3E_FID = N.G3E_FID
        JOIN CELE_NOR_GRP_CAT@GTECH E ON E.NORMA = N.NORMA
        JOIN EINTERRU_AT@GTECH I ON I.CODIGO = N.CIRCUITO
        JOIN CCONECTIVIDAD_E@GTECH Z ON I.G3E_FID = Z.G3E_FID
        WHERE B.G3E_FNO = 17100 AND B.ESTADO = 'OPERACION'  AND C.TIPO LIKE '%PRIMARIO%'
              AND E.TIPO_RED = 'PRIMARIA' AND N.NORMA NOT IN ('SPT','712','710','711','730','731')
              AND C.TIPO_INSTALACION IS NULL AND N.CIRCUITO = :circuito AND B.REGION = :regional
    """,
    "POSTES_BT": """
        SELECT DISTINCT C.G3E_FID, C.CODIGO, B.CODIGO_OPERATIVO,N.MACRONORMA,
            N.CIRCUITO,B.REGION,N.CODIGO_TRAFO, CASE WHEN Z.TENSION >= '13.8' THEN '2'
                                             WHEN Z.TENSION = '34.5' THEN '3'
                                             WHEN Z.TENSION <= '115' THEN '4' END NIVEL_TENSION,
            B.MUNICIPIO, B.UBICACION, B.CONTRATO_INSTALACION, B.CLASIFICACION_MERCADO,
            B.FECHA_INSTALACION, B.OBSERVACIONES, N.NORMA,
            CASE WHEN C.TIPO_INSTALACION IS NULL THEN 'Poste' ELSE C.TIPO_INSTALACION END APOYO,
            C.MATERIAL, C.ALTURA, E.TIPO_ADECUACION, C.RESISTENCIA_KGF, C.CODIGO CODIGO2, B.UC, E.TIPO_RED,
            B.COOR_GPS_LON,B.COOR_GPS_LAT
        FROM CCOMUN@GTECH B
        JOIN EPOSTE_AT@GTECH C ON B.G3E_FID = C.G3E_FID
        JOIN NORMA@GTECH N ON C.G3E_FID = N.G3E_FID
        JOIN CELE_NOR_GRP_CAT@GTECH E ON E.NORMA = N.NORMA
        JOIN EINTERRU_AT@GTECH I ON I.CODIGO = N.CIRCUITO
        JOIN CCONECTIVIDAD_E@GTECH Z ON I.G3E_FID = Z.G3E_FID
        WHERE B.G3E_FNO = 17100 AND B.ESTADO = 'OPERACION'  AND C.TIPO = 'SECUNDARIO'
              AND E.TIPO_RED = 'SECUNDARIA' AND N.NORMA NOT IN ('328','PT','CA_BAJA','STOP','BAJANTE','BancoCliente')
              AND C.TIPO_INSTALACION IS NULL AND N.CIRCUITO = :circuito AND B.REGION = :regional
    """,
    "RED_MT": """
        SELECT L.G3E_FID, C.CODIGO_OPERATIVO, AT.CODIGO, AT.CODE_CONDUCTOR, E.NODO1_ID,E.NODO2_ID,E.TENSION,
            C.CONTRATO_INSTALACION, C.SUBREGION, C.MUNICIPIO, C.OBSERVACIONES, E.FASES,
            E.LONGITUD / 1000 AS LONGITUD, AT.TIPO_AISLAMIENTO, E.LOCALIZACION, C.CLASIFICACION_MERCADO,
            E.CIRCUITO, C.REGION,C.UC, C.FECHA_INSTALACION,
            GetOrdinateValue(G3E_GEOMETRY, 1) AS LON1, GetOrdinateValue(G3E_GEOMETRY, 2) AS LAT1,
            GetOrdinateValue(G3E_GEOMETRY, 4) AS LON2, GetOrdinateValue(G3E_GEOMETRY, 5) AS LAT2
        FROM ECON_PRI_LN@GTECH L
        JOIN CCOMUN@GTECH C ON L.G3E_FID = C.G3E_FID
        JOIN ECON_PRI_AT@GTECH AT ON AT.G3E_FID = L.G3E_FID
        JOIN CCONECTIVIDAD_E@GTECH E ON AT.G3E_FID = E.G3E_FID
        WHERE C.ESTADO = 'OPERACION'  AND E.CIRCUITO = :circuito AND C.REGION = :regional
    """,
    "RED_BT": """
            SELECT L.G3E_FID, AT.CODIGO, AT.CODE_CONDUCTOR, C.OT_MAXIMO, 
            C.CONTRATO_INSTALACION, C.SUBREGION, C.MUNICIPIO, 
            E.LONGITUD / 1000 AS LONGITUD, E.NODO_TRANSFORM_V, 
            E.LOCALIZACION, C.CLASIFICACION_MERCADO, 
            E.CIRCUITO, C.REGION, C.FECHA_INSTALACION,
            E.FASES,
            GetOrdinateValue(G3E_GEOMETRY, 1) AS LON1, GetOrdinateValue(G3E_GEOMETRY, 2) AS LAT1,
            GetOrdinateValue(G3E_GEOMETRY, 4) AS LON2, GetOrdinateValue(G3E_GEOMETRY, 5) AS LAT2
        FROM ECON_SES_LN@GTECH L
        JOIN CCOMUN@GTECH C ON L.G3E_FID = C.G3E_FID
        JOIN ECON_SES_AT@GTECH AT ON AT.G3E_FID = L.G3E_FID
        JOIN CCONECTIVIDAD_E@GTECH E ON AT.G3E_FID = E.G3E_FID
        WHERE C.ESTADO = 'OPERACION' AND E.LONGITUD > 3 AND E.CIRCUITO = :circuito AND C.REGION = :regional
    """,
    "POSTES_BT_BY_TRAFO": """
        SELECT DISTINCT C.G3E_FID, C.CODIGO, B.CODIGO_OPERATIVO,N.MACRONORMA,
            N.CIRCUITO,B.REGION,N.CODIGO_TRAFO, CASE WHEN Z.TENSION >= '13.8' THEN '2'
            WHEN Z.TENSION = '34.5' THEN '3'
            WHEN Z.TENSION <= '115' THEN '4' END NIVEL_TENSION,
            B.MUNICIPIO, B.UBICACION, B.CONTRATO_INSTALACION, B.CLASIFICACION_MERCADO,
            B.FECHA_INSTALACION, B.OBSERVACIONES, N.NORMA,
            CASE WHEN C.TIPO_INSTALACION IS NULL THEN 'Poste' ELSE C.TIPO_INSTALACION END APOYO,
            C.MATERIAL, C.ALTURA, E.TIPO_ADECUACION, C.RESISTENCIA_KGF, C.CODIGO CODIGO2, B.UC, E.TIPO_RED,
            B.COOR_GPS_LON,B.COOR_GPS_LAT
        FROM CCOMUN@GTECH B
        JOIN EPOSTE_AT@GTECH C ON B.G3E_FID = C.G3E_FID
        JOIN NORMA@GTECH N ON C.G3E_FID = N.G3E_FID
        JOIN CELE_NOR_GRP_CAT@GTECH E ON E.NORMA = N.NORMA
        JOIN EINTERRU_AT@GTECH I ON I.CODIGO = N.CIRCUITO
        JOIN CCONECTIVIDAD_E@GTECH Z ON I.G3E_FID = Z.G3E_FID
        WHERE B.G3E_FNO = 17100  AND B.ESTADO = 'OPERACION'  
        AND E.TIPO_RED = 'SECUNDARIA' AND N.NORMA NOT IN ('328','PT','CA_BAJA','STOP','BAJANTE','BancoCliente')
        AND N.CODIGO_TRAFO = :codigo_trafo
        AND B.REGION = :regional
    """,
    "RED_BT_BY_TRAFO": """
    SELECT L.G3E_FID, AT.CODIGO, AT.CODE_CONDUCTOR, C.OT_MAXIMO ,C.CONTRATO_INSTALACION,
           C.SUBREGION, C.MUNICIPIO, E.LONGITUD / 1000 AS LONGITUD, 
           E.NODO_TRANSFORM_V, E.LOCALIZACION, C.CLASIFICACION_MERCADO, 
           E.CIRCUITO, C.REGION, C.FECHA_INSTALACION,E.FASES,
           GetOrdinateValue(G3E_GEOMETRY, 1) AS LON1,
           GetOrdinateValue(G3E_GEOMETRY, 2) AS LAT1,
           GetOrdinateValue(G3E_GEOMETRY, 4) AS LON2,
           GetOrdinateValue(G3E_GEOMETRY, 5) AS LAT2
    FROM ECON_SES_LN@GTECH L
    JOIN CCOMUN@GTECH C ON L.G3E_FID = C.G3E_FID
    JOIN ECON_SES_AT@GTECH AT ON AT.G3E_FID = L.G3E_FID
    JOIN CCONECTIVIDAD_E@GTECH E ON AT.G3E_FID = E.G3E_FID
    WHERE C.ESTADO = 'OPERACION' 
      AND E.NODO_TRANSFORM_V = :codigo_trafo
      AND C.REGION = :regional
    """,
    "TRAFOS_POR_CIRCUITO": """
    SELECT DISTINCT C.NODO_TRANSFORM_V AS CODIGO_TRAFO,A.CAPACIDAD_NOMINAL
    FROM CCONECTIVIDAD_E@GTECH A
    JOIN CCOMUN@GTECH B ON A.G3E_FID = B.G3E_FID
    JOIN ETRANSFO_AT@GTECH C ON B.G3E_FID = C.G3E_FID
    WHERE A.G3E_FNO = 20400
      AND B.ESTADO = 'OPERACION'
      AND A.CIRCUITO = :circuito
      AND B.REGION = :regional
    ORDER BY C.NODO_TRANSFORM_V
    """,
    "TRAFOS_POR_CIRCUITO_PDF": """
SELECT DISTINCT A.NODO_TRANSFORM_V AS CODIGO_TRAFO, A.CAPACIDAD_NOMINAL
FROM CCONECTIVIDAD_E@GTECH A
JOIN CCOMUN@GTECH B ON A.G3E_FID = B.G3E_FID
JOIN ETRANSFO_AT@GTECH C ON B.G3E_FID = C.G3E_FID
WHERE A.G3E_FNO = 20400
  AND B.ESTADO = 'OPERACION'
  AND A.CIRCUITO = :circuito
  AND B.REGION = :regional
ORDER BY A.NODO_TRANSFORM_V
    """
}
